<?php

use Illuminate\Database\Seeder;

class TipoSubcatTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tipo_subcat = array(
                  array('id' => '1','codigo' => '14010-0100','sub_categoria_id' => '1','descripcion' => 'Máquinas calibradoras de pintura'),
                  array('id' => '2','codigo' => '14010-0101','sub_categoria_id' => '1','descripcion' => 'Máquinas cepilladoras'),
                  array('id' => '3','codigo' => '14010-0102','sub_categoria_id' => '1','descripcion' => 'Máquinas cortadoras y terminadoras de engranaje'),
                  array('id' => '4','codigo' => '14010-0103','sub_categoria_id' => '1','descripcion' => 'Máquinas de cortadura al arco'),
                  array('id' => '5','codigo' => '14010-0104','sub_categoria_id' => '1','descripcion' => 'Máquinas de coser industriales'),
                  array('id' => '6','codigo' => '14010-0105','sub_categoria_id' => '1','descripcion' => 'Máquinas disparadoras'),
                  array('id' => '7','codigo' => '14010-0106','sub_categoria_id' => '1','descripcion' => 'Máquinas embaladoras'),
                  array('id' => '8','codigo' => '14010-0107','sub_categoria_id' => '1','descripcion' => 'Máquinas empaquetadoras'),
                  array('id' => '9','codigo' => '14010-0108','sub_categoria_id' => '1','descripcion' => 'Máquinas engrapadoras (excepto las de tipo de oficina)'),
                  array('id' => '10','codigo' => '14010-0109','sub_categoria_id' => '1','descripcion' => 'Máquinas escariadoras'),
                  array('id' => '11','codigo' => '14010-0110','sub_categoria_id' => '1','descripcion' => 'Máquinas esclopadoras'),
                  array('id' => '12','codigo' => '14010-0111','sub_categoria_id' => '1','descripcion' => 'Máquinas estañadoras'),
                  array('id' => '13','codigo' => '14010-0112','sub_categoria_id' => '1','descripcion' => 'Máquinas etiquetadoras'),
                  array('id' => '14','codigo' => '14010-0113','sub_categoria_id' => '1','descripcion' => 'Máquinas dibujadoras'),
                  array('id' => '15','codigo' => '14010-0114','sub_categoria_id' => '1','descripcion' => 'Máquinas fraguadoras'),
                  array('id' => '16','codigo' => '14010-0115','sub_categoria_id' => '1','descripcion' => 'Máquinas laminadoras para carnets'),
                  array('id' => '17','codigo' => '14010-0116','sub_categoria_id' => '1','descripcion' => 'Máquinas limadoras'),
                  array('id' => '18','codigo' => '14010-0117','sub_categoria_id' => '1','descripcion' => 'Máquinas para doblar tubos'),
                  array('id' => '19','codigo' => '14010-0118','sub_categoria_id' => '1','descripcion' => 'Máquinas para hacer chompines'),
                  array('id' => '20','codigo' => '14010-0119','sub_categoria_id' => '1','descripcion' => 'Máquinas para hacer llaves'),
                  array('id' => '21','codigo' => '14010-0120','sub_categoria_id' => '1','descripcion' => 'Máquinas recobradoras de fudente'),
                  array('id' => '22','codigo' => '14010-0121','sub_categoria_id' => '1','descripcion' => 'Máquinas roscadoras'),
                  array('id' => '23','codigo' => '14010-0122','sub_categoria_id' => '1','descripcion' => 'Máquinas roscadoras de tornillos'),
                  array('id' => '24','codigo' => '14010-0123','sub_categoria_id' => '1','descripcion' => 'Máquinas soldadoras de punto'),
                  array('id' => '25','codigo' => '14010-0124','sub_categoria_id' => '1','descripcion' => 'Máquinas selladoras de paquetes'),
                  array('id' => '26','codigo' => '14010-0125','sub_categoria_id' => '1','descripcion' => 'Máquinas torcedoras y formadoras'),
                  array('id' => '27','codigo' => '14010-0126','sub_categoria_id' => '1','descripcion' => 'Máquinas universales para latonería dobladora y envarilladora'),
                  array('id' => '28','codigo' => '14010-0127','sub_categoria_id' => '1','descripcion' => 'Marcos para segueta'),
                  array('id' => '29','codigo' => '14010-0128','sub_categoria_id' => '1','descripcion' => 'Martillos'),
                  array('id' => '30','codigo' => '14010-0129','sub_categoria_id' => '1','descripcion' => 'Martillos neumáticos'),
                  array('id' => '31','codigo' => '14010-0130','sub_categoria_id' => '1','descripcion' => 'Máscaras para soldador'),
                  array('id' => '32','codigo' => '14010-0131','sub_categoria_id' => '1','descripcion' => 'Máscaras protectoras'),
                  array('id' => '33','codigo' => '14010-0132','sub_categoria_id' => '1','descripcion' => 'Mazos'),
                  array('id' => '34','codigo' => '14010-0133','sub_categoria_id' => '1','descripcion' => 'Medidores de presión'),
                  array('id' => '35','codigo' => '14010-0134','sub_categoria_id' => '1','descripcion' => 'Mesones para mecánico'),
                  array('id' => '36','codigo' => '14010-0135','sub_categoria_id' => '1','descripcion' => 'Metalizadores'),
                  array('id' => '37','codigo' => '14010-0136','sub_categoria_id' => '1','descripcion' => 'Micrómetros'),
                  array('id' => '38','codigo' => '14010-0137','sub_categoria_id' => '1','descripcion' => 'Motones'),
                  array('id' => '39','codigo' => '14010-0138','sub_categoria_id' => '1','descripcion' => 'Motores a explosión'),
                  array('id' => '40','codigo' => '14010-0139','sub_categoria_id' => '1','descripcion' => 'Motores diésel'),
                  array('id' => '41','codigo' => '14010-0140','sub_categoria_id' => '1','descripcion' => 'Motores eléctricos'),
                  array('id' => '42','codigo' => '14010-0141','sub_categoria_id' => '1','descripcion' => 'Niveles'),
                  array('id' => '43','codigo' => '14010-0142','sub_categoria_id' => '1','descripcion' => 'Numeradores de golpe (punzones)'),
                  array('id' => '44','codigo' => '14010-0143','sub_categoria_id' => '1','descripcion' => 'Palas'),
                  array('id' => '45','codigo' => '14010-0144','sub_categoria_id' => '1','descripcion' => 'Pasadores para llaves de copa'),
                  array('id' => '46','codigo' => '14010-0145','sub_categoria_id' => '1','descripcion' => 'Perforadoras'),
                  array('id' => '47','codigo' => '14010-0146','sub_categoria_id' => '1','descripcion' => 'Pinzas'),
                  array('id' => '48','codigo' => '14010-0147','sub_categoria_id' => '1','descripcion' => 'Pisones'),
                  array('id' => '49','codigo' => '14010-0148','sub_categoria_id' => '1','descripcion' => 'Pistolas de aire'),
                  array('id' => '50','codigo' => '14010-0149','sub_categoria_id' => '1','descripcion' => 'Plantas eléctricas (pequeñas)'),
                  array('id' => '51','codigo' => '14010-0150','sub_categoria_id' => '1','descripcion' => 'Poleas'),
                  array('id' => '52','codigo' => '14010-0151','sub_categoria_id' => '1','descripcion' => 'Prensas'),
                  array('id' => '53','codigo' => '14010-0152','sub_categoria_id' => '1','descripcion' => 'Prensas hidráulicas'),
                  array('id' => '54','codigo' => '14010-0153','sub_categoria_id' => '1','descripcion' => 'Pulidoras-lijadoras'),
                  array('id' => '55','codigo' => '14010-0154','sub_categoria_id' => '1','descripcion' => 'Punzonadoras'),
                  array('id' => '56','codigo' => '14010-0155','sub_categoria_id' => '1','descripcion' => 'Punzones'),
                  array('id' => '57','codigo' => '14010-0156','sub_categoria_id' => '1','descripcion' => 'Quemadores'),
                  array('id' => '58','codigo' => '14010-0157','sub_categoria_id' => '1','descripcion' => 'Raches'),
                  array('id' => '59','codigo' => '14010-0158','sub_categoria_id' => '1','descripcion' => 'Rasquetas'),
                  array('id' => '60','codigo' => '14010-0159','sub_categoria_id' => '1','descripcion' => 'Rectificadores de corriente'),
                  array('id' => '61','codigo' => '14010-0160','sub_categoria_id' => '1','descripcion' => 'Reflectores'),
                  array('id' => '62','codigo' => '14010-0161','sub_categoria_id' => '1','descripcion' => 'Reguladores de aire'),
                  array('id' => '63','codigo' => '14010-0162','sub_categoria_id' => '1','descripcion' => 'Reguladores de velocidad'),
                  array('id' => '64','codigo' => '14010-0163','sub_categoria_id' => '1','descripcion' => 'Relays'),
                  array('id' => '65','codigo' => '14010-0164','sub_categoria_id' => '1','descripcion' => 'Remachadoras'),
                  array('id' => '66','codigo' => '14010-0165','sub_categoria_id' => '1','descripcion' => 'Rumas'),
                  array('id' => '67','codigo' => '14010-0166','sub_categoria_id' => '1','descripcion' => 'Romanas'),
                  array('id' => '68','codigo' => '14010-0167','sub_categoria_id' => '1','descripcion' => 'Sacabocados'),
                  array('id' => '69','codigo' => '14010-0168','sub_categoria_id' => '1','descripcion' => 'Sargentos de carpintera'),
                  array('id' => '70','codigo' => '14010-0169','sub_categoria_id' => '1','descripcion' => 'Seguetas eléctricas'),
                  array('id' => '71','codigo' => '14010-0170','sub_categoria_id' => '1','descripcion' => 'Señoritas (polipasto)'),
                  array('id' => '72','codigo' => '14010-0171','sub_categoria_id' => '1','descripcion' => 'Serruchos'),
                  array('id' => '73','codigo' => '14010-0172','sub_categoria_id' => '1','descripcion' => 'Sierras'),
                  array('id' => '74','codigo' => '14010-0173','sub_categoria_id' => '1','descripcion' => 'Sirenas'),
                  array('id' => '75','codigo' => '14010-0174','sub_categoria_id' => '1','descripcion' => 'Soldadores'),
                  array('id' => '76','codigo' => '14010-0175','sub_categoria_id' => '1','descripcion' => 'Soldadores de punto'),
                  array('id' => '77','codigo' => '14010-0176','sub_categoria_id' => '1','descripcion' => 'Sopladores'),
                  array('id' => '78','codigo' => '14010-0177','sub_categoria_id' => '1','descripcion' => 'Sopletes'),
                  array('id' => '79','codigo' => '14010-0178','sub_categoria_id' => '1','descripcion' => 'Soportes'),
                  array('id' => '80','codigo' => '14010-0179','sub_categoria_id' => '1','descripcion' => 'Tableros de soldadura'),
                  array('id' => '81','codigo' => '14010-0180','sub_categoria_id' => '1','descripcion' => 'Tableros eléctricos'),
                  array('id' => '82','codigo' => '14010-0181','sub_categoria_id' => '1','descripcion' => 'Tableros para herramientas'),
                  array('id' => '83','codigo' => '14010-0182','sub_categoria_id' => '1','descripcion' => 'Taladros'),
                  array('id' => '84','codigo' => '14010-0183','sub_categoria_id' => '1','descripcion' => 'Tamizadores'),
                  array('id' => '85','codigo' => '14010-0184','sub_categoria_id' => '1','descripcion' => 'Tanques de sedimentación'),
                  array('id' => '86','codigo' => '14010-0185','sub_categoria_id' => '1','descripcion' => 'Tenazas'),
                  array('id' => '87','codigo' => '14010-0186','sub_categoria_id' => '1','descripcion' => 'Termómetros'),
                  array('id' => '88','codigo' => '14010-0187','sub_categoria_id' => '1','descripcion' => 'Terrajas'),
                  array('id' => '89','codigo' => '14010-0188','sub_categoria_id' => '1','descripcion' => 'Tornos'),
                  array('id' => '90','codigo' => '14010-0189','sub_categoria_id' => '1','descripcion' => 'Trajes de amianto'),
                  array('id' => '91','codigo' => '14010-0190','sub_categoria_id' => '1','descripcion' => 'Transformadores eléctricos'),
                  array('id' => '92','codigo' => '14010-0191','sub_categoria_id' => '1','descripcion' => 'Trompos para carpintera'),
                  array('id' => '93','codigo' => '14010-0192','sub_categoria_id' => '1','descripcion' => 'Troqueladores'),
                  array('id' => '94','codigo' => '14010-0193','sub_categoria_id' => '1','descripcion' => 'Turbinas'),
                  array('id' => '95','codigo' => '14010-0194','sub_categoria_id' => '1','descripcion' => 'Winches'),
                  array('id' => '96','codigo' => '14010-0195','sub_categoria_id' => '1','descripcion' => 'Yunques'),
                  array('id' => '97','codigo' => '14010-0196','sub_categoria_id' => '1','descripcion' => 'Zunchadoras'),
                  array('id' => '98','codigo' => '14010-0197','sub_categoria_id' => '1','descripcion' => 'Abre-trochas'),
                  array('id' => '99','codigo' => '14010-0198','sub_categoria_id' => '1','descripcion' => 'Andamios corredizos para túneles'),
                  array('id' => '100','codigo' => '14010-0199','sub_categoria_id' => '1','descripcion' => 'Andamios corredizos para concretar túneles'),
                  array('id' => '101','codigo' => '14010-0200','sub_categoria_id' => '1','descripcion' => 'Andamios metálicos'),
                  array('id' => '102','codigo' => '14010-0201','sub_categoria_id' => '1','descripcion' => 'Apisonadoras'),
                  array('id' => '103','codigo' => '14010-0202','sub_categoria_id' => '1','descripcion' => 'Aplanadoras'),
                  array('id' => '104','codigo' => '14010-0203','sub_categoria_id' => '1','descripcion' => 'Aplanadoras de vibración'),
                  array('id' => '105','codigo' => '14010-0204','sub_categoria_id' => '1','descripcion' => 'Aplanadoras de madera'),
                  array('id' => '106','codigo' => '14010-0205','sub_categoria_id' => '1','descripcion' => 'Aserradoras de piedra'),
                  array('id' => '107','codigo' => '14010-0206','sub_categoria_id' => '1','descripcion' => 'Asfaltadoras'),
                  array('id' => '108','codigo' => '14010-0207','sub_categoria_id' => '1','descripcion' => 'Bombeadoras de concreto'),
                  array('id' => '109','codigo' => '14010-0208','sub_categoria_id' => '1','descripcion' => 'Cabrestantes'),
                  array('id' => '110','codigo' => '14010-0209','sub_categoria_id' => '1','descripcion' => 'Cabrias'),
                  array('id' => '111','codigo' => '14010-0210','sub_categoria_id' => '1','descripcion' => 'Calentadores para asfalto'),
                  array('id' => '112','codigo' => '14010-0211','sub_categoria_id' => '1','descripcion' => 'Camiones-mezcladoras de concreto'),
                  array('id' => '113','codigo' => '14010-0212','sub_categoria_id' => '1','descripcion' => 'Cargadoras de piedra'),
                  array('id' => '114','codigo' => '14010-0213','sub_categoria_id' => '1','descripcion' => 'Cargadores de cangilones'),
                  array('id' => '115','codigo' => '14010-0214','sub_categoria_id' => '1','descripcion' => 'Carros para túneles (jumbos)'),
                  array('id' => '116','codigo' => '14010-0215','sub_categoria_id' => '1','descripcion' => 'Centrífugas de asfalto'),
                  array('id' => '117','codigo' => '14010-0216','sub_categoria_id' => '1','descripcion' => 'Clasificadoras y lavadoras de arena y grava'),
                  array('id' => '118','codigo' => '14010-0217','sub_categoria_id' => '1','descripcion' => 'Comprensores'),
                  array('id' => '119','codigo' => '14010-0218','sub_categoria_id' => '1','descripcion' => 'Cortadoras de cabillas'),
                  array('id' => '120','codigo' => '14010-0219','sub_categoria_id' => '1','descripcion' => 'Distribuidoras de asfalto'),
                  array('id' => '121','codigo' => '14010-0220','sub_categoria_id' => '1','descripcion' => 'Dobladoras de cabillas'),
                  array('id' => '122','codigo' => '14010-0221','sub_categoria_id' => '1','descripcion' => 'Dragas'),
                  array('id' => '123','codigo' => '14010-0222','sub_categoria_id' => '1','descripcion' => 'Equipos de perforación'),
                  array('id' => '124','codigo' => '14010-0223','sub_categoria_id' => '1','descripcion' => 'Equipos drag-line para palas mecánicas'),
                  array('id' => '125','codigo' => '14010-0224','sub_categoria_id' => '1','descripcion' => 'Escarificadoras (reoters)'),
                  array('id' => '126','codigo' => '14010-0225','sub_categoria_id' => '1','descripcion' => 'Escobas mecánicas'),
                  array('id' => '127','codigo' => '14010-0226','sub_categoria_id' => '1','descripcion' => 'Escoplos de cadena'),
                  array('id' => '128','codigo' => '14010-0227','sub_categoria_id' => '1','descripcion' => 'Esparcidoras de arena'),
                  array('id' => '129','codigo' => '14010-0228','sub_categoria_id' => '1','descripcion' => 'Esparcidoras de materiales'),
                  array('id' => '130','codigo' => '14010-0229','sub_categoria_id' => '1','descripcion' => 'Excavadoras'),
                  array('id' => '131','codigo' => '14010-0230','sub_categoria_id' => '1','descripcion' => 'Extractores hidráulicos para pernos de orugas'),
                  array('id' => '132','codigo' => '14010-0231','sub_categoria_id' => '1','descripcion' => 'Furgonetas'),
                  array('id' => '133','codigo' => '14010-0232','sub_categoria_id' => '1','descripcion' => 'Grúas (móviles)'),
                  array('id' => '134','codigo' => '14010-0233','sub_categoria_id' => '1','descripcion' => 'Herramientas de construcción'),
                  array('id' => '135','codigo' => '14010-0234','sub_categoria_id' => '1','descripcion' => 'Inyectadoras de cemento'),
                  array('id' => '136','codigo' => '14010-0235','sub_categoria_id' => '1','descripcion' => 'Malacates'),
                  array('id' => '137','codigo' => '14010-0236','sub_categoria_id' => '1','descripcion' => 'Máquinas barredoras'),
                  array('id' => '138','codigo' => '14010-0237','sub_categoria_id' => '1','descripcion' => 'Máquinas derretidoras-esparcidoras de asfalto'),
                  array('id' => '139','codigo' => '14010-0238','sub_categoria_id' => '1','descripcion' => 'Máquinas para armar y desarmar orugas'),
                  array('id' => '140','codigo' => '14010-0239','sub_categoria_id' => '1','descripcion' => 'Máquinas para descoser sacos de cemento'),
                  array('id' => '141','codigo' => '14010-0240','sub_categoria_id' => '1','descripcion' => 'Máquinas para fabricar bloques de concreto'),
                  array('id' => '142','codigo' => '14010-0241','sub_categoria_id' => '1','descripcion' => 'Máquinas para marcar caminos'),
                  array('id' => '143','codigo' => '14010-0242','sub_categoria_id' => '1','descripcion' => 'Máquinas para trozar madera'),
                  array('id' => '144','codigo' => '14010-0243','sub_categoria_id' => '1','descripcion' => 'Máquinas secadoras de arena para asfalto'),
                  array('id' => '145','codigo' => '14010-0244','sub_categoria_id' => '1','descripcion' => 'Máquinas terra-cobra'),
                  array('id' => '146','codigo' => '14010-0245','sub_categoria_id' => '1','descripcion' => 'Martillos para clavar pilotes'),
                  array('id' => '147','codigo' => '14010-0246','sub_categoria_id' => '1','descripcion' => 'Martillos para ensayos de suelos'),
                  array('id' => '148','codigo' => '14010-0247','sub_categoria_id' => '1','descripcion' => 'Martillos perforadores'),
                  array('id' => '149','codigo' => '14010-0248','sub_categoria_id' => '1','descripcion' => 'Martillos rompedores neumáticos'),
                  array('id' => '150','codigo' => '14010-0249','sub_categoria_id' => '1','descripcion' => 'Martillos rotativos'),
                  array('id' => '151','codigo' => '14010-0250','sub_categoria_id' => '1','descripcion' => 'Martinetes'),
                  array('id' => '152','codigo' => '14010-0251','sub_categoria_id' => '1','descripcion' => 'Mezcladoras de asfalto'),
                  array('id' => '153','codigo' => '14010-0252','sub_categoria_id' => '1','descripcion' => 'Mezcladoras de concreto'),
                  array('id' => '154','codigo' => '14010-0253','sub_categoria_id' => '1','descripcion' => 'Montacargas'),
                  array('id' => '155','codigo' => '14010-0254','sub_categoria_id' => '1','descripcion' => 'Motobombas'),
                  array('id' => '156','codigo' => '14010-0255','sub_categoria_id' => '1','descripcion' => 'Motoniveladoras'),
                  array('id' => '157','codigo' => '14010-0256','sub_categoria_id' => '1','descripcion' => 'Niveladora (bulldozers)'),
                  array('id' => '158','codigo' => '14010-0257','sub_categoria_id' => '1','descripcion' => 'Niveladora de ángulo (anglodozers)'),
                  array('id' => '159','codigo' => '14010-0258','sub_categoria_id' => '1','descripcion' => 'Palas cargadoras'),
                  array('id' => '160','codigo' => '14010-0259','sub_categoria_id' => '1','descripcion' => 'Palas mecánicas'),
                  array('id' => '161','codigo' => '14010-0260','sub_categoria_id' => '1','descripcion' => 'Patas de cabra'),
                  array('id' => '162','codigo' => '14010-0261','sub_categoria_id' => '1','descripcion' => 'Pavimentadoras'),
                  array('id' => '163','codigo' => '14010-0262','sub_categoria_id' => '1','descripcion' => 'Payloaders'),
                  array('id' => '164','codigo' => '14010-0263','sub_categoria_id' => '1','descripcion' => 'Perforadoras de pozos'),
                  array('id' => '165','codigo' => '14010-0264','sub_categoria_id' => '1','descripcion' => 'Petrolizadoras'),
                  array('id' => '166','codigo' => '14010-0265','sub_categoria_id' => '1','descripcion' => 'Picadoras de piedras'),
                  array('id' => '167','codigo' => '14010-0266','sub_categoria_id' => '1','descripcion' => 'Plantas clasificadoras de agregados'),
                  array('id' => '168','codigo' => '14010-0267','sub_categoria_id' => '1','descripcion' => 'Plantas mezcladoras de asfalto'),
                  array('id' => '169','codigo' => '14010-0268','sub_categoria_id' => '1','descripcion' => 'Plataformas para mantenimiento de pistas de aviación'),
                  array('id' => '170','codigo' => '14010-0269','sub_categoria_id' => '1','descripcion' => 'Pulvi-mezcladoras'),
                  array('id' => '171','codigo' => '14010-0270','sub_categoria_id' => '1','descripcion' => 'Remachadoras'),
                  array('id' => '172','codigo' => '14010-0271','sub_categoria_id' => '1','descripcion' => 'Rociadoras'),
                  array('id' => '173','codigo' => '14010-0272','sub_categoria_id' => '1','descripcion' => 'Rociadoras de arena'),
                  array('id' => '174','codigo' => '14010-0273','sub_categoria_id' => '1','descripcion' => 'Rodillos'),
                  array('id' => '175','codigo' => '14010-0274','sub_categoria_id' => '1','descripcion' => 'Secadoras de arena'),
                  array('id' => '176','codigo' => '14010-0275','sub_categoria_id' => '1','descripcion' => 'Taladros sobre carretillo'),
                  array('id' => '177','codigo' => '14010-0276','sub_categoria_id' => '1','descripcion' => 'Tanques de remolque'),
                  array('id' => '178','codigo' => '14010-0277','sub_categoria_id' => '1','descripcion' => 'Tanque para concreto'),
                  array('id' => '179','codigo' => '14010-0278','sub_categoria_id' => '1','descripcion' => 'Tanques petrolizadores de remolque'),
                  array('id' => '180','codigo' => '14010-0279','sub_categoria_id' => '1','descripcion' => 'Tolvas'),
                  array('id' => '181','codigo' => '14010-0280','sub_categoria_id' => '1','descripcion' => 'Torres de elevación'),
                  array('id' => '182','codigo' => '14010-0281','sub_categoria_id' => '1','descripcion' => 'Tournapulls'),
                  array('id' => '183','codigo' => '14010-0282','sub_categoria_id' => '1','descripcion' => 'Tractores'),
                  array('id' => '184','codigo' => '14010-0283','sub_categoria_id' => '1','descripcion' => 'Traillas'),
                  array('id' => '185','codigo' => '14010-0284','sub_categoria_id' => '1','descripcion' => 'Transportadores de bandas'),
                  array('id' => '186','codigo' => '14010-0285','sub_categoria_id' => '1','descripcion' => 'Traxcavators'),
                  array('id' => '187','codigo' => '14010-0286','sub_categoria_id' => '1','descripcion' => 'Tree-dozers'),
                  array('id' => '188','codigo' => '14010-0287','sub_categoria_id' => '1','descripcion' => 'Trituradoras de piedras'),
                  array('id' => '189','codigo' => '14010-0288','sub_categoria_id' => '1','descripcion' => 'Troleys'),
                  array('id' => '190','codigo' => '14010-0289','sub_categoria_id' => '1','descripcion' => 'Vagonetas'),
                  array('id' => '191','codigo' => '14010-0290','sub_categoria_id' => '1','descripcion' => 'Vibradores de concreto'),
                  array('id' => '192','codigo' => '14010-0291','sub_categoria_id' => '1','descripcion' => 'Vibradores de vigas'),
                  array('id' => '193','codigo' => '14010-0292','sub_categoria_id' => '1','descripcion' => 'Vibradores neumáticos'),
                  array('id' => '194','codigo' => '14010-0293','sub_categoria_id' => '1','descripcion' => 'Zanjadoras'),
                  array('id' => '195','codigo' => '14010-0294','sub_categoria_id' => '1','descripcion' => 'Zorras'),


                  array('id' => '196','codigo' => '14020-0001','sub_categoria_id' => '2','descripcion' => 'Ajustadores de bombas de frenos'),
                  array('id' => '197','codigo' => '14020-0002','sub_categoria_id' => '2','descripcion' => 'Alineadores'),
                  array('id' => '198','codigo' => '14020-0003','sub_categoria_id' => '2','descripcion' => 'Aparatos para limpiar bujías'),
                  array('id' => '199','codigo' => '14020-0004','sub_categoria_id' => '2','descripcion' => 'Aparatos para reparar frenos'),
                  array('id' => '200','codigo' => '14020-0005','sub_categoria_id' => '2','descripcion' => 'Apretadores de tuercas'),
                  array('id' => '201','codigo' => '14020-0006','sub_categoria_id' => '2','descripcion' => 'Bancos de pruebas'),
                  array('id' => '202','codigo' => '14020-0007','sub_categoria_id' => '2','descripcion' => 'Cargadores de batería'),
                  array('id' => '203','codigo' => '14020-0008','sub_categoria_id' => '2','descripcion' => 'Colocadores de anillos'),
                  array('id' => '204','codigo' => '14020-0009','sub_categoria_id' => '2','descripcion' => 'Engrasadores'),
                  array('id' => '205','codigo' => '14020-0010','sub_categoria_id' => '2','descripcion' => 'Equipos de engrase'),
                  array('id' => '206','codigo' => '14020-0011','sub_categoria_id' => '2','descripcion' => 'Equipos para cambios de aceite'),
                  array('id' => '207','codigo' => '14020-0012','sub_categoria_id' => '2','descripcion' => 'Equipos para entonar motores'),
                  array('id' => '208','codigo' => '14020-0013','sub_categoria_id' => '2','descripcion' => 'Equipos para lavar radiadores'),
                  array('id' => '209','codigo' => '14020-0014','sub_categoria_id' => '2','descripcion' => 'Equipos para prueba de mecanismos aviones'),
                  array('id' => '210','codigo' => '14020-0015','sub_categoria_id' => '2','descripcion' => 'Equipos para reparar cauchos y tripas'),
                  array('id' => '211','codigo' => '14020-0016','sub_categoria_id' => '2','descripcion' => 'Equipos para reparar parafangos'),
                  array('id' => '212','codigo' => '14020-0017','sub_categoria_id' => '2','descripcion' => 'Esmeriladoras de válvulas'),
                  array('id' => '213','codigo' => '14020-0018','sub_categoria_id' => '2','descripcion' => 'Estrados para sostener aviones durante su reparación'),
                  array('id' => '214','codigo' => '14020-0019','sub_categoria_id' => '2','descripcion' => 'Extractores'),
                  array('id' => '215','codigo' => '14020-0020','sub_categoria_id' => '2','descripcion' => 'Extractores de aceite'),
                  array('id' => '216','codigo' => '14020-0021','sub_categoria_id' => '2','descripcion' => 'Gatos carretos'),
                  array('id' => '217','codigo' => '14020-0022','sub_categoria_id' => '2','descripcion' => 'Gatos extensores'),
                  array('id' => '218','codigo' => '14020-0023','sub_categoria_id' => '2','descripcion' => 'Gatos extractores'),
                  array('id' => '219','codigo' => '14020-0024','sub_categoria_id' => '2','descripcion' => 'Herramientas de taller'),
                  array('id' => '220','codigo' => '14020-0025','sub_categoria_id' => '2','descripcion' => 'Lavadoras de vehículos'),
                  array('id' => '221','codigo' => '14020-0026','sub_categoria_id' => '2','descripcion' => 'Limpiadoras a vapor'),
                  array('id' => '222','codigo' => '14020-0027','sub_categoria_id' => '2','descripcion' => 'Limpiadoras a vapor'),
                  array('id' => '223','codigo' => '14020-0028','sub_categoria_id' => '2','descripcion' => 'Lubricadores'),
                  array('id' => '224','codigo' => '14020-0029','sub_categoria_id' => '2','descripcion' => 'Máquinas cambiadoras de cauchos'),
                  array('id' => '225','codigo' => '14020-0030','sub_categoria_id' => '2','descripcion' => 'Máquinas de hacer estoperas'),
                  array('id' => '226','codigo' => '14020-0031','sub_categoria_id' => '2','descripcion' => 'Máquinas descarbonizadoras de pistones'),
                  array('id' => '227','codigo' => '14020-0032','sub_categoria_id' => '2','descripcion' => 'Máquinas lavadoras de carros'),
                  array('id' => '228','codigo' => '14020-0033','sub_categoria_id' => '2','descripcion' => 'Máquinas para bandas de frenos'),
                  array('id' => '229','codigo' => '14020-0034','sub_categoria_id' => '2','descripcion' => 'Máquinas para remendar zapatas de frenos'),
                  array('id' => '230','codigo' => '14020-0035','sub_categoria_id' => '2','descripcion' => 'Máquinas de quitaruedas'),
                  array('id' => '231','codigo' => '14020-0036','sub_categoria_id' => '2','descripcion' => 'Medidores de presión de aire'),
                  array('id' => '232','codigo' => '14020-0037','sub_categoria_id' => '2','descripcion' => 'Pistolas de engrase'),
                  array('id' => '233','codigo' => '14020-0038','sub_categoria_id' => '2','descripcion' => 'Pistolas para bombas de gasolina'),
                  array('id' => '234','codigo' => '14020-0039','sub_categoria_id' => '2','descripcion' => 'Pistolas para gasoil'),
                  array('id' => '235','codigo' => '14020-0040','sub_categoria_id' => '2','descripcion' => 'Probadores'),
                  array('id' => '236','codigo' => '14020-0041','sub_categoria_id' => '2','descripcion' => 'Pulidoras de cilindros'),
                  array('id' => '237','codigo' => '14020-0042','sub_categoria_id' => '2','descripcion' => 'Rectificadoras'),
                  array('id' => '238','codigo' => '14020-0043','sub_categoria_id' => '2','descripcion' => 'Remachadoras de bandas de frenos'),
                  array('id' => '239','codigo' => '14020-0044','sub_categoria_id' => '2','descripcion' => 'Sincronizadores de distribuidores'),
                  array('id' => '240','codigo' => '14020-0045','sub_categoria_id' => '2','descripcion' => 'Suministradores de grasas'),
                  array('id' => '241','codigo' => '14020-0046','sub_categoria_id' => '2','descripcion' => 'Testers'),
                  array('id' => '242','codigo' => '14020-0047','sub_categoria_id' => '2','descripcion' => 'Valvulineras'),
                  array('id' => '243','codigo' => '14020-0048','sub_categoria_id' => '2','descripcion' => 'Vulcanizadoras'),


                  array('id' => '244','codigo' => '14030-0002','sub_categoria_id' => '3','descripcion' => 'Aparatos para digestión de proteínas'),
                  array('id' => '245','codigo' => '14030-0004','sub_categoria_id' => '3','descripcion' => 'Arados'),
                  array('id' => '246','codigo' => '14030-0005','sub_categoria_id' => '3','descripcion' => 'Artesas'),
                  array('id' => '247','codigo' => '14030-0006','sub_categoria_id' => '3','descripcion' => 'Arreos y atalajes'),
                  array('id' => '248','codigo' => '14030-0007','sub_categoria_id' => '3','descripcion' => 'Asperjadoras'),
                  array('id' => '249','codigo' => '14030-0008','sub_categoria_id' => '3','descripcion' => 'Aventadores para el beneficio del café'),
                  array('id' => '250','codigo' => '14030-0009','sub_categoria_id' => '3','descripcion' => 'Azadas'),
                  array('id' => '251','codigo' => '14030-0010','sub_categoria_id' => '3','descripcion' => 'Azadones'),
                  array('id' => '252','codigo' => '14030-0011','sub_categoria_id' => '3','descripcion' => 'Bombas'),
                  array('id' => '253','codigo' => '14030-0012','sub_categoria_id' => '3','descripcion' => 'Carretas'),
                  array('id' => '254','codigo' => '14030-0013','sub_categoria_id' => '3','descripcion' => 'Centrífugas'),
                  array('id' => '255','codigo' => '14030-0014','sub_categoria_id' => '3','descripcion' => 'Cintas de agrimensores'),
                  array('id' => '256','codigo' => '14030-0015','sub_categoria_id' => '3','descripcion' => 'Clasificadoras para granos'),
                  array('id' => '257','codigo' => '14030-0016','sub_categoria_id' => '3','descripcion' => 'Conejeras metalicas'),
                  array('id' => '258','codigo' => '14030-0017','sub_categoria_id' => '3','descripcion' => 'Cortadoras'),
                  array('id' => '259','codigo' => '14030-0018','sub_categoria_id' => '3','descripcion' => 'Cosechadoras'),
                  array('id' => '260','codigo' => '14030-0019','sub_categoria_id' => '3','descripcion' => 'Criadoras avícolas'),
                  array('id' => '261','codigo' => '14030-0020','sub_categoria_id' => '3','descripcion' => 'Cultivadoras'),
                  array('id' => '262','codigo' => '14030-0021','sub_categoria_id' => '3','descripcion' => 'Desarraigadoras de tocones'),
                  array('id' => '263','codigo' => '14030-0022','sub_categoria_id' => '3','descripcion' => 'Desfibradoras'),
                  array('id' => '264','codigo' => '14030-0023','sub_categoria_id' => '3','descripcion' => 'Desgranadoras'),
                  array('id' => '265','codigo' => '14030-0024','sub_categoria_id' => '3','descripcion' => 'Desmontadoras de café'),
                  array('id' => '266','codigo' => '14030-0025','sub_categoria_id' => '3','descripcion' => 'Desterronadoras'),
                  array('id' => '267','codigo' => '14030-0026','sub_categoria_id' => '3','descripcion' => 'Digestores para análisis de caña'),
                  array('id' => '268','codigo' => '14030-0027','sub_categoria_id' => '3','descripcion' => 'Distribuidoras de abonos'),
                  array('id' => '269','codigo' => '14030-0028','sub_categoria_id' => '3','descripcion' => 'Esmasculadoras'),
                  array('id' => '270','codigo' => '14030-0029','sub_categoria_id' => '3','descripcion' => 'Enfriadoras eléctricas de leche'),
                  array('id' => '271','codigo' => '14030-0030','sub_categoria_id' => '3','descripcion' => 'Equipos para análisis de suelos'),
                  array('id' => '272','codigo' => '14030-0031','sub_categoria_id' => '3','descripcion' => 'Escardillas'),
                  array('id' => '273','codigo' => '14030-0032','sub_categoria_id' => '3','descripcion' => 'Escarificadoras'),
                  array('id' => '274','codigo' => '14030-0033','sub_categoria_id' => '3','descripcion' => 'Espolvoreadoras (máquina)'),
                  array('id' => '275','codigo' => '14030-0034','sub_categoria_id' => '3','descripcion' => 'Estercoleras'),
                  array('id' => '276','codigo' => '14030-0035','sub_categoria_id' => '3','descripcion' => 'Exprimidoras de lana'),
                  array('id' => '277','codigo' => '14030-0036','sub_categoria_id' => '3','descripcion' => 'Extirpadoras'),
                  array('id' => '278','codigo' => '14030-0037','sub_categoria_id' => '3','descripcion' => 'Fertilizadoras'),
                  array('id' => '279','codigo' => '14030-0038','sub_categoria_id' => '3','descripcion' => 'Fumigadoras'),
                  array('id' => '280','codigo' => '14030-0039','sub_categoria_id' => '3','descripcion' => 'Germinadoras'),
                  array('id' => '281','codigo' => '14030-0040','sub_categoria_id' => '3','descripcion' => 'Gradas'),
                  array('id' => '282','codigo' => '14030-0041','sub_categoria_id' => '3','descripcion' => 'Incubadoras'),
                  array('id' => '283','codigo' => '14030-0042','sub_categoria_id' => '3','descripcion' => 'Jaulas'),
                  array('id' => '284','codigo' => '14030-0043','sub_categoria_id' => '3','descripcion' => 'Lavadoras de café'),
                  array('id' => '285','codigo' => '14030-0044','sub_categoria_id' => '3','descripcion' => 'Máquinas extractoras de grasa'),
                  array('id' => '286','codigo' => '14030-0045','sub_categoria_id' => '3','descripcion' => 'Máquinas homogeneizadoras'),
                  array('id' => '287','codigo' => '14030-0046','sub_categoria_id' => '3','descripcion' => 'Máquinas para cortar epitelios'),
                  array('id' => '288','codigo' => '14030-0047','sub_categoria_id' => '3','descripcion' => 'Máquinas para cortar forrajes'),
                  array('id' => '289','codigo' => '14030-0048','sub_categoria_id' => '3','descripcion' => 'Máquinas para matar bachacos'),
                  array('id' => '290','codigo' => '14030-0049','sub_categoria_id' => '3','descripcion' => 'Máquinas perforadoras agrícolas'),
                  array('id' => '291','codigo' => '14030-0050','sub_categoria_id' => '3','descripcion' => 'Máquinas secadoras para granos'),
                  array('id' => '292','codigo' => '14030-0051','sub_categoria_id' => '3','descripcion' => 'Molinos'),
                  array('id' => '293','codigo' => '14030-0052','sub_categoria_id' => '3','descripcion' => 'Motocultores'),
                  array('id' => '294','codigo' => '14030-0053','sub_categoria_id' => '3','descripcion' => 'Ordeñadoras mecánicas'),
                  array('id' => '295','codigo' => '14030-0054','sub_categoria_id' => '3','descripcion' => 'Ovoscopios'),
                  array('id' => '296','codigo' => '14030-0055','sub_categoria_id' => '3','descripcion' => 'Pailas'),
                  array('id' => '297','codigo' => '14030-0056','sub_categoria_id' => '3','descripcion' => 'Palomares (móviles)'),
                  array('id' => '298','codigo' => '14030-0057','sub_categoria_id' => '3','descripcion' => 'Picadoras (máquinas)'),
                  array('id' => '299','codigo' => '14030-0058','sub_categoria_id' => '3','descripcion' => 'Podadoras (máquinas)'),
                  array('id' => '300','codigo' => '14030-0059','sub_categoria_id' => '3','descripcion' => 'Pulidoras de granos'),
                  array('id' => '301','codigo' => '14030-0060','sub_categoria_id' => '3','descripcion' => 'Pulverizadores'),
                  array('id' => '302','codigo' => '14030-0061','sub_categoria_id' => '3','descripcion' => 'Rastrillos y rastras aradoras'),
                  array('id' => '303','codigo' => '14030-0062','sub_categoria_id' => '3','descripcion' => 'Rociadoras'),
                  array('id' => '304','codigo' => '14030-0063','sub_categoria_id' => '3','descripcion' => 'Rodillos agrícolas'),
                  array('id' => '305','codigo' => '14030-0064','sub_categoria_id' => '3','descripcion' => 'Rolos'),
                  array('id' => '306','codigo' => '14030-0065','sub_categoria_id' => '3','descripcion' => 'Secadoras'),
                  array('id' => '307','codigo' => '14030-0066','sub_categoria_id' => '3','descripcion' => 'Segadoras'),
                  array('id' => '308','codigo' => '14030-0067','sub_categoria_id' => '3','descripcion' => 'Segadoras de grama'),
                  array('id' => '309','codigo' => '14030-0068','sub_categoria_id' => '3','descripcion' => 'Sembradoras'),
                  array('id' => '310','codigo' => '14030-0069','sub_categoria_id' => '3','descripcion' => 'Silos (móviles)'),
                  array('id' => '311','codigo' => '14030-0070','sub_categoria_id' => '3','descripcion' => 'Sillas de montar'),
                  array('id' => '312','codigo' => '14030-0071','sub_categoria_id' => '3','descripcion' => 'Tanques y depósitos'),
                  array('id' => '313','codigo' => '14030-0072','sub_categoria_id' => '3','descripcion' => 'Tractores agrícolas'),
                  array('id' => '314','codigo' => '14030-0073','sub_categoria_id' => '3','descripcion' => 'Trallas agrícolas'),
                  array('id' => '315','codigo' => '14030-0074','sub_categoria_id' => '3','descripcion' => 'Trapiches'),
                  array('id' => '316','codigo' => '14030-0075','sub_categoria_id' => '3','descripcion' => 'Trilladoras'),
                  array('id' => '317','codigo' => '14030-0076','sub_categoria_id' => '3','descripcion' => 'Trozeros'),
                  array('id' => '318','codigo' => '14030-0077','sub_categoria_id' => '3','descripcion' => 'Ventiladores de granos'),
                  array('id' => '319','codigo' => '14030-0078','sub_categoria_id' => '3','descripcion' => 'Zanjadoras agrícolas'),


                  array('id' => '320','codigo' => '14040-0001','sub_categoria_id' => '4','descripcion' => 'Biseladoras-encuadernadoras'),
                  array('id' => '321','codigo' => '14040-0002','sub_categoria_id' => '4','descripcion' => 'Cajas de madera para guarniciones'),
                  array('id' => '322','codigo' => '14040-0003','sub_categoria_id' => '4','descripcion' => 'Cisnadoras-perforadoras'),
                  array('id' => '323','codigo' => '14040-0004','sub_categoria_id' => '4','descripcion' => 'Cizallas de mano'),
                  array('id' => '324','codigo' => '14040-0005','sub_categoria_id' => '4','descripcion' => 'Coleros eléctricos'),
                  array('id' => '325','codigo' => '14040-0006','sub_categoria_id' => '4','descripcion' => 'Cortadoras de clisés'),
                  array('id' => '326','codigo' => '14040-0007','sub_categoria_id' => '4','descripcion' => 'Cortadoras índice'),
                  array('id' => '327','codigo' => '14040-0008','sub_categoria_id' => '4','descripcion' => 'Cosedoras (máquinas)'),
                  array('id' => '328','codigo' => '14040-0009','sub_categoria_id' => '4','descripcion' => 'Chivaletes'),
                  array('id' => '329','codigo' => '14040-0010','sub_categoria_id' => '4','descripcion' => 'Decnígrafos paragón'),
                  array('id' => '330','codigo' => '14040-0011','sub_categoria_id' => '4','descripcion' => 'Dobladoras'),
                  array('id' => '331','codigo' => '14040-0012','sub_categoria_id' => '4','descripcion' => 'Editoras portátiles'),
                  array('id' => '332','codigo' => '14040-0013','sub_categoria_id' => '4','descripcion' => 'Empaquetadoras'),
                  array('id' => '333','codigo' => '14040-0014','sub_categoria_id' => '4','descripcion' => 'Engrapadoras tipográficas'),
                  array('id' => '334','codigo' => '14040-0015','sub_categoria_id' => '4','descripcion' => 'Equipos de dibujo'),
                  array('id' => '335','codigo' => '14040-0016','sub_categoria_id' => '4','descripcion' => 'Equipos de fotograbado'),
                  array('id' => '336','codigo' => '14040-0017','sub_categoria_id' => '4','descripcion' => 'Equipos de zincograbado'),
                  array('id' => '337','codigo' => '14040-0018','sub_categoria_id' => '4','descripcion' => 'Equipos litográficos'),
                  array('id' => '338','codigo' => '14040-0019','sub_categoria_id' => '4','descripcion' => 'Foliadoras-numeradoras'),
                  array('id' => '339','codigo' => '14040-0020','sub_categoria_id' => '4','descripcion' => 'Fotograbadoras'),
                  array('id' => '340','codigo' => '14040-0021','sub_categoria_id' => '4','descripcion' => 'Fresadoras'),
                  array('id' => '341','codigo' => '14040-0022','sub_categoria_id' => '4','descripcion' => 'Fuentes de tipos'),
                  array('id' => '342','codigo' => '14040-0023','sub_categoria_id' => '4','descripcion' => 'Fundidoras de plomo'),
                  array('id' => '343','codigo' => '14040-0024','sub_categoria_id' => '4','descripcion' => 'Grabadoras eléctricas tipo-gráficas'),
                  array('id' => '344','codigo' => '14040-0025','sub_categoria_id' => '4','descripcion' => 'Graneadoras para planchas litográficas'),
                  array('id' => '345','codigo' => '14040-0026','sub_categoria_id' => '4','descripcion' => 'Guillotinas para panel'),
                  array('id' => '346','codigo' => '14040-0027','sub_categoria_id' => '4','descripcion' => 'Hornillos'),
                  array('id' => '347','codigo' => '14040-0028','sub_categoria_id' => '4','descripcion' => 'Impresoras de fotografía'),
                  array('id' => '348','codigo' => '14040-0029','sub_categoria_id' => '4','descripcion' => 'Invertidoras de imagen'),
                  array('id' => '349','codigo' => '14040-0030','sub_categoria_id' => '4','descripcion' => 'Lámparas de arco'),
                  array('id' => '350','codigo' => '14040-0031','sub_categoria_id' => '4','descripcion' => 'Lavadoras de planchas'),
                  array('id' => '351','codigo' => '14040-0032','sub_categoria_id' => '4','descripcion' => 'Linotipos'),
                  array('id' => '352','codigo' => '14040-0033','sub_categoria_id' => '4','descripcion' => 'Máquinas biseladoras'),
                  array('id' => '353','codigo' => '14040-0034','sub_categoria_id' => '4','descripcion' => 'Máquinas cortadoras interlíneas'),
                  array('id' => '354','codigo' => '14040-0035','sub_categoria_id' => '4','descripcion' => 'Máquinas de proceso a gelatina'),
                  array('id' => '355','codigo' => '14040-0036','sub_categoria_id' => '4','descripcion' => 'Máquina cosedoras'),
                  array('id' => '356','codigo' => '14040-0037','sub_categoria_id' => '4','descripcion' => 'Máquinas de proceso a offset'),
                  array('id' => '357','codigo' => '14040-0038','sub_categoria_id' => '4','descripcion' => 'Máquinas encuadernadoras'),
                  array('id' => '358','codigo' => '14040-0039','sub_categoria_id' => '4','descripcion' => 'Máquinas heliográficas'),
                  array('id' => '359','codigo' => '14040-0040','sub_categoria_id' => '4','descripcion' => 'Máquinas intertipe automáticas'),
                  array('id' => '360','codigo' => '14040-0041','sub_categoria_id' => '4','descripcion' => 'Máquinas para adolar'),
                  array('id' => '361','codigo' => '14040-0042','sub_categoria_id' => '4','descripcion' => 'Máquinas para bordear planos'),
                  array('id' => '362','codigo' => '14040-0043','sub_categoria_id' => '4','descripcion' => 'Máquinas para dorar a fuego'),
                  array('id' => '363','codigo' => '14040-0044','sub_categoria_id' => '4','descripcion' => 'Máquinas para empastar libros'),
                  array('id' => '364','codigo' => '14040-0045','sub_categoria_id' => '4','descripcion' => 'Máquinas para fabricar sobres'),
                  array('id' => '365','codigo' => '14040-0046','sub_categoria_id' => '4','descripcion' => 'Máquinas para formar cajas'),
                  array('id' => '366','codigo' => '14040-0047','sub_categoria_id' => '4','descripcion' => 'Máquinas para fundiciones'),
                  array('id' => '367','codigo' => '14040-0048','sub_categoria_id' => '4','descripcion' => 'Máquinas para hacer sellos'),
                  array('id' => '368','codigo' => '14040-0049','sub_categoria_id' => '4','descripcion' => 'Máquinas para pegar sobres'),
                  array('id' => '369','codigo' => '14040-0050','sub_categoria_id' => '4','descripcion' => 'Máquinas para trazar círculos y óvulos'),
                  array('id' => '370','codigo' => '14040-0051','sub_categoria_id' => '4','descripcion' => 'Máquinas realizadoras de imprenta'),
                  array('id' => '371','codigo' => '14040-0052','sub_categoria_id' => '4','descripcion' => 'Máquinas secadoras automáticas'),
                  array('id' => '372','codigo' => '14040-0053','sub_categoria_id' => '4','descripcion' => 'Monotipos'),
                  array('id' => '373','codigo' => '14040-0054','sub_categoria_id' => '4','descripcion' => 'Perforadoras para tipografía'),
                  array('id' => '374','codigo' => '14040-0055','sub_categoria_id' => '4','descripcion' => 'Prensas impresoras (otras)'),
                  array('id' => '375','codigo' => '14040-0056','sub_categoria_id' => '4','descripcion' => 'Prensas litográficas'),
                  array('id' => '376','codigo' => '14040-0057','sub_categoria_id' => '4','descripcion' => 'Prensas para ponchar'),
                  array('id' => '377','codigo' => '14040-0058','sub_categoria_id' => '4','descripcion' => 'Prensas para tipografía'),
                  array('id' => '378','codigo' => '14040-0059','sub_categoria_id' => '4','descripcion' => 'Prensas planas'),
                  array('id' => '379','codigo' => '14040-0060','sub_categoria_id' => '4','descripcion' => 'Rayadoras'),
                  array('id' => '380','codigo' => '14040-0061','sub_categoria_id' => '4','descripcion' => 'Ribeteadoras'),
                  array('id' => '381','codigo' => '14040-0062','sub_categoria_id' => '4','descripcion' => 'Rotativas'),
                  array('id' => '382','codigo' => '14040-0063','sub_categoria_id' => '4','descripcion' => 'Sacapuntas'),
                  array('id' => '383','codigo' => '14040-0064','sub_categoria_id' => '4','descripcion' => 'Sierras-cepilladoras'),
                  array('id' => '384','codigo' => '14040-0065','sub_categoria_id' => '4','descripcion' => 'Sifones para lavar impresos'),
                  array('id' => '385','codigo' => '14040-0066','sub_categoria_id' => '4','descripcion' => 'Tituladoras'),
                  array('id' => '386','codigo' => '14040-0067','sub_categoria_id' => '4','descripcion' => 'Torneadoras'),
                  array('id' => '387','codigo' => '14040-0068','sub_categoria_id' => '4','descripcion' => 'Troqueladoras'),


                  array('id' => '388','codigo' => '14050-0001','sub_categoria_id' => '5','descripcion' => 'Maquinarias y equipos industriales'),
                  array('id' => '389','codigo' => '14050-0002','sub_categoria_id' => '5','descripcion' => 'Maquinarias y equipos de taller'),


                  array('id' => '390','codigo' => '14060-0001','sub_categoria_id' => '6','descripcion' => 'Calderas'),
                  array('id' => '391','codigo' => '14060-0002','sub_categoria_id' => '6','descripcion' => 'Generadores'),
                  array('id' => '392','codigo' => '14060-0003','sub_categoria_id' => '6','descripcion' => 'Motores'),
                  array('id' => '393','codigo' => '14060-0004','sub_categoria_id' => '6','descripcion' => 'Turbinas'),


                  array('id' => '394','codigo' => '14070-0001','sub_categoria_id' => '7','descripcion' => 'Maquinarias y equipos de riego'),
                  array('id' => '395','codigo' => '14070-0002','sub_categoria_id' => '7','descripcion' => 'Maquinarias y equipos de acueductos'),


                  array('id' => '396','codigo' => '14080-0001','sub_categoria_id' => '8','descripcion' => 'Equipos de almacén'),


                  array('id' => '397','codigo' => '14990-0001','sub_categoria_id' => '9','descripcion' => 'Otras maquinarias y demás equipos de construcción, campo, industria y taller'),


                  array('id' => '398','codigo' => '15010-0001','sub_categoria_id' => '10','descripcion' => 'Ambulancias'),
                  array('id' => '399','codigo' => '15010-0002','sub_categoria_id' => '10','descripcion' => 'Autobuses'),
                  array('id' => '400','codigo' => '15010-0003','sub_categoria_id' => '10','descripcion' => 'Automóviles'),
                  array('id' => '401','codigo' => '15010-0004','sub_categoria_id' => '10','descripcion' => 'Camiones cisterna para asfalto'),
                  array('id' => '402','codigo' => '15010-0005','sub_categoria_id' => '10','descripcion' => 'Camiones cisterna para agua'),
                  array('id' => '403','codigo' => '15010-0006','sub_categoria_id' => '10','descripcion' => 'Camiones cisterna para gasolina'),
                  array('id' => '404','codigo' => '15010-0007','sub_categoria_id' => '10','descripcion' => 'Camiones cisterna para gas'),
                  array('id' => '405','codigo' => '15010-0008','sub_categoria_id' => '10','descripcion' => 'Camiones chasis'),
                  array('id' => '406','codigo' => '15010-0009','sub_categoria_id' => '10','descripcion' => 'Camiones de estacas'),
                  array('id' => '407','codigo' => '15010-0010','sub_categoria_id' => '10','descripcion' => 'Camiones volteos'),
                  array('id' => '408','codigo' => '15010-0011','sub_categoria_id' => '10','descripcion' => 'Camiones ganaderos'),
                  array('id' => '409','codigo' => '15010-0012','sub_categoria_id' => '10','descripcion' => 'Camiones grúas'),
                  array('id' => '410','codigo' => '15010-0013','sub_categoria_id' => '10','descripcion' => 'Camiones para basura'),
                  array('id' => '411','codigo' => '15010-0014','sub_categoria_id' => '10','descripcion' => 'Camionetas de carga cubiertas'),
                  array('id' => '412','codigo' => '15010-0015','sub_categoria_id' => '10','descripcion' => 'Camionetas de carga pick-up'),
                  array('id' => '413','codigo' => '15010-0016','sub_categoria_id' => '10','descripcion' => 'Camionetas de pasajeros'),
                  array('id' => '414','codigo' => '15010-0017','sub_categoria_id' => '10','descripcion' => 'Camionetas (ómnibus rurales)'),
                  array('id' => '415','codigo' => '15010-0019','sub_categoria_id' => '10','descripcion' => 'Carros bombas para incendios'),
                  array('id' => '416','codigo' => '15010-0020','sub_categoria_id' => '10','descripcion' => 'Carros de bomberos'),
                  array('id' => '417','codigo' => '15010-0021','sub_categoria_id' => '10','descripcion' => 'Chutos'),
                  array('id' => '418','codigo' => '15010-0022','sub_categoria_id' => '10','descripcion' => 'Escaleras automóviles para bomberos'),
                  array('id' => '419','codigo' => '15010-0023','sub_categoria_id' => '10','descripcion' => 'Furgones'),
                  array('id' => '420','codigo' => '15010-0024','sub_categoria_id' => '10','descripcion' => 'Gandolas'),
                  array('id' => '421','codigo' => '15010-0025','sub_categoria_id' => '10','descripcion' => 'Microbúses'),
                  array('id' => '422','codigo' => '15010-0026','sub_categoria_id' => '10','descripcion' => 'Motocicletas'),
                  array('id' => '423','codigo' => '15010-0027','sub_categoria_id' => '10','descripcion' => 'Motocicletas de reparto'),
                  array('id' => '424','codigo' => '15010-0028','sub_categoria_id' => '10','descripcion' => 'Motonetas'),
                  array('id' => '425','codigo' => '15010-0029','sub_categoria_id' => '10','descripcion' => 'Motonetas de reparto'),
                  array('id' => '426','codigo' => '15010-0030','sub_categoria_id' => '10','descripcion' => 'Radiopatrullas'),
                  array('id' => '427','codigo' => '15010-0031','sub_categoria_id' => '10','descripcion' => 'Transportadores de vehículos'),


                  array('id' => '428','codigo' => '15020-0001','sub_categoria_id' => '11','descripcion' => 'Autovías'),
                  array('id' => '429','codigo' => '15020-0002','sub_categoria_id' => '11','descripcion' => 'Grúas ferroviarias automotores'),
                  array('id' => '430','codigo' => '15020-0003','sub_categoria_id' => '11','descripcion' => 'Locomotoras a vapor'),
                  array('id' => '431','codigo' => '15020-0004','sub_categoria_id' => '11','descripcion' => 'Locomotoras diésel'),
                  array('id' => '432','codigo' => '15020-0005','sub_categoria_id' => '11','descripcion' => 'Locomotoras eléctricas'),
                  array('id' => '433','codigo' => '15020-0006','sub_categoria_id' => '11','descripcion' => 'Tranvías'),
                  array('id' => '434','codigo' => '15020-0007','sub_categoria_id' => '11','descripcion' => 'Trolle (trolley)'),
                  array('id' => '435','codigo' => '15020-0008','sub_categoria_id' => '11','descripcion' => 'Vagones de mercancías cubiertos'),
                  array('id' => '436','codigo' => '15020-0009','sub_categoria_id' => '11','descripcion' => 'Vagones para carga de cables aéreos'),
                  array('id' => '437','codigo' => '15020-0010','sub_categoria_id' => '11','descripcion' => 'Vagones de mercancías de bordes altos'),
                  array('id' => '438','codigo' => '15020-0011','sub_categoria_id' => '11','descripcion' => 'Vagones de mercancías de bordes bajos'),
                  array('id' => '439','codigo' => '15020-0012','sub_categoria_id' => '11','descripcion' => 'Vagones de pasajeros'),
                  array('id' => '440','codigo' => '15020-0013','sub_categoria_id' => '11','descripcion' => 'Vagones para pasajeros de cables aéreos'),
                  array('id' => '441','codigo' => '15020-0014','sub_categoria_id' => '11','descripcion' => 'Vagones de tracción propia'),
                  array('id' => '442','codigo' => '15020-0015','sub_categoria_id' => '11','descripcion' => 'Vagones grúa'),
                  array('id' => '443','codigo' => '15020-0016','sub_categoria_id' => '11','descripcion' => 'Vagones plataforma'),
                  array('id' => '444','codigo' => '15020-0017','sub_categoria_id' => '11','descripcion' => 'Vagones refrigerantes'),
                  array('id' => '445','codigo' => '15020-0018','sub_categoria_id' => '11','descripcion' => 'Vagones tanque'),
                  array('id' => '446','codigo' => '15020-0019','sub_categoria_id' => '11','descripcion' => 'Vagones tolva'),
                  array('id' => '447','codigo' => '15020-0020','sub_categoria_id' => '11','descripcion' => 'Vagones volquete'),
                  array('id' => '448','codigo' => '15020-0021','sub_categoria_id' => '11','descripcion' => 'Vagonetas'),


                  array('id' => '449','codigo' => '15030-0001','sub_categoria_id' => '12','descripcion' => 'Balandras'),
                  array('id' => '450','codigo' => '15030-0002','sub_categoria_id' => '12','descripcion' => 'Barcos cargueros'),
                  array('id' => '451','codigo' => '15030-0003','sub_categoria_id' => '12','descripcion' => 'Barcos de guerra (reservado ministerio de la defensa)'),
                  array('id' => '452','codigo' => '15030-0004','sub_categoria_id' => '12','descripcion' => 'Barcos de río'),
                  array('id' => '453','codigo' => '15030-0005','sub_categoria_id' => '12','descripcion' => 'Barcos de salvamento y de rescate'),
                  array('id' => '454','codigo' => '15030-0006','sub_categoria_id' => '12','descripcion' => 'Barcos extintores de incendio'),
                  array('id' => '455','codigo' => '15030-0007','sub_categoria_id' => '12','descripcion' => 'Barcos furgoneros'),
                  array('id' => '456','codigo' => '15030-0008','sub_categoria_id' => '12','descripcion' => 'Barcos mixtos de carga y pasajeros'),
                  array('id' => '457','codigo' => '15030-0009','sub_categoria_id' => '12','descripcion' => 'Barcos pesqueros'),
                  array('id' => '458','codigo' => '15030-0010','sub_categoria_id' => '12','descripcion' => 'Barcos refrigerantes'),
                  array('id' => '459','codigo' => '15030-0011','sub_categoria_id' => '12','descripcion' => 'Barcos taller'),
                  array('id' => '460','codigo' => '15030-0012','sub_categoria_id' => '12','descripcion' => 'Barcos tanqueros'),
                  array('id' => '461','codigo' => '15030-0013','sub_categoria_id' => '12','descripcion' => 'Botes'),
                  array('id' => '462','codigo' => '15030-0014','sub_categoria_id' => '12','descripcion' => 'Buques-faro'),
                  array('id' => '463','codigo' => '15030-0015','sub_categoria_id' => '12','descripcion' => 'Gabarras'),
                  array('id' => '464','codigo' => '15030-0016','sub_categoria_id' => '12','descripcion' => 'Lanchas'),
                  array('id' => '465','codigo' => '15030-0017','sub_categoria_id' => '12','descripcion' => 'Remolcadores'),
                  array('id' => '466','codigo' => '15030-0018','sub_categoria_id' => '12','descripcion' => 'Veleros'),
                  array('id' => '467','codigo' => '15030-0019','sub_categoria_id' => '12','descripcion' => 'Yates'),


                  array('id' => '468','codigo' => '15040-0001','sub_categoria_id' => '13','descripcion' => 'Aviones de carga'),
                  array('id' => '469','codigo' => '15040-0002','sub_categoria_id' => '13','descripcion' => 'Aviones de pasajeros'),
                  array('id' => '470','codigo' => '15040-0003','sub_categoria_id' => '13','descripcion' => 'Avionetas'),
                  array('id' => '471','codigo' => '15040-0004','sub_categoria_id' => '13','descripcion' => 'Dirigibles'),
                  array('id' => '472','codigo' => '15040-0005','sub_categoria_id' => '13','descripcion' => 'Helicópteros'),
                  array('id' => '473','codigo' => '15040-0006','sub_categoria_id' => '13','descripcion' => 'Planeadores'),


                  array('id' => '474','codigo' => '15050-0001','sub_categoria_id' => '14','descripcion' => 'Bicicletas'),
                  array('id' => '475','codigo' => '15050-0002','sub_categoria_id' => '14','descripcion' => 'Coches de tracción animal'),
                  array('id' => '476','codigo' => '15050-0003','sub_categoria_id' => '14','descripcion' => 'Triciclos'),
                  array('id' => '477','codigo' => '15050-0004','sub_categoria_id' => '14','descripcion' => 'Remolques'),
                  array('id' => '478','codigo' => '15050-0005','sub_categoria_id' => '14','descripcion' => 'Zorras'),


                  array('id' => '479','codigo' => '15060-0001','sub_categoria_id' => '15','descripcion' => 'Boyas'),
                  array('id' => '480','codigo' => '15060-0002','sub_categoria_id' => '15','descripcion' => 'Camiones especiales para aeropuertos'),
                  array('id' => '481','codigo' => '15060-0003','sub_categoria_id' => '15','descripcion' => 'Encerados para camión'),
                  array('id' => '482','codigo' => '15060-0004','sub_categoria_id' => '15','descripcion' => 'Escafandras'),
                  array('id' => '483','codigo' => '15060-0005','sub_categoria_id' => '15','descripcion' => 'Escalerillas para aviones'),
                  array('id' => '484','codigo' => '15060-0006','sub_categoria_id' => '15','descripcion' => 'Gabarras'),
                  array('id' => '485','codigo' => '15060-0007','sub_categoria_id' => '15','descripcion' => 'Grúas flotantes'),
                  array('id' => '486','codigo' => '15060-0008','sub_categoria_id' => '15','descripcion' => 'Grúas móviles'),
                  array('id' => '487','codigo' => '15060-0009','sub_categoria_id' => '15','descripcion' => 'Montacargas automotores'),
                  array('id' => '488','codigo' => '15060-0010','sub_categoria_id' => '15','descripcion' => 'Motores fuera de borda'),
                  array('id' => '489','codigo' => '15060-0011','sub_categoria_id' => '15','descripcion' => 'Motores marinos'),
                  array('id' => '490','codigo' => '15060-0012','sub_categoria_id' => '15','descripcion' => 'Remolcadores (chocones)'),
                  array('id' => '491','codigo' => '15060-0013','sub_categoria_id' => '15','descripcion' => 'Remolques'),
                  array('id' => '492','codigo' => '15060-0014','sub_categoria_id' => '15','descripcion' => 'Remolques especiales para aeropuertos'),
                  array('id' => '493','codigo' => '15060-0015','sub_categoria_id' => '15','descripcion' => 'Señales de tránsito'),
                  array('id' => '494','codigo' => '15060-0016','sub_categoria_id' => '15','descripcion' => 'Transportadores de vehículos'),
                  array('id' => '495','codigo' => '15060-0017','sub_categoria_id' => '15','descripcion' => 'Vagonetas'),
                  array('id' => '496','codigo' => '15060-0018','sub_categoria_id' => '15','descripcion' => 'Zorras'),


                  array('id' => '497','codigo' => '15990-0001','sub_categoria_id' => '16','descripcion' => 'Otros equipos de transporte, tracción y elevación'),


                  array('id' => '498','codigo' => '16010-0001','sub_categoria_id' => '17','descripcion' => 'Amplificadores'),
                  array('id' => '499','codigo' => '16010-0002','sub_categoria_id' => '17','descripcion' => 'Analizadoras'),
                  array('id' => '500','codigo' => '16010-0003','sub_categoria_id' => '17','descripcion' => 'Antenas fácilmente desmontables'),
                  array('id' => '501','codigo' => '16010-0004','sub_categoria_id' => '17','descripcion' => 'Centrales telefónicas manuales'),
                  array('id' => '502','codigo' => '16010-0005','sub_categoria_id' => '17','descripcion' => 'Concentradores'),
                  array('id' => '503','codigo' => '16010-0006','sub_categoria_id' => '17','descripcion' => 'Conmutadores telefónicos'),
                  array('id' => '504','codigo' => '16010-0007','sub_categoria_id' => '17','descripcion' => 'Conmutadores telegráficos'),
                  array('id' => '505','codigo' => '16010-0008','sub_categoria_id' => '17','descripcion' => 'Equipos de control remoto'),
                  array('id' => '506','codigo' => '16010-0009','sub_categoria_id' => '17','descripcion' => 'Equipos de sloran'),
                  array('id' => '507','codigo' => '16010-0010','sub_categoria_id' => '17','descripcion' => 'Equipos de luces de señales para torres de antena'),
                  array('id' => '508','codigo' => '16010-0011','sub_categoria_id' => '17','descripcion' => 'Equipos de radar'),
                  array('id' => '509','codigo' => '16010-0012','sub_categoria_id' => '17','descripcion' => 'Equipos de radiocomunicación portátiles'),
                  array('id' => '510','codigo' => '16010-0013','sub_categoria_id' => '17','descripcion' => 'Equipos de comunicación interna (intercomunicadores)'),
                  array('id' => '511','codigo' => '16010-0014','sub_categoria_id' => '17','descripcion' => 'Generadores de señales'),
                  array('id' => '512','codigo' => '16010-0015','sub_categoria_id' => '17','descripcion' => 'Jacks panels'),
                  array('id' => '513','codigo' => '16010-0016','sub_categoria_id' => '17','descripcion' => 'Manipuladores'),
                  array('id' => '514','codigo' => '16010-0017','sub_categoria_id' => '17','descripcion' => 'Mesas para teleimpresoras'),
                  array('id' => '515','codigo' => '16010-0018','sub_categoria_id' => '17','descripcion' => 'Micrófonos'),
                  array('id' => '516','codigo' => '16010-0019','sub_categoria_id' => '17','descripcion' => 'Multicanales para telefonía'),
                  array('id' => '517','codigo' => '16010-0020','sub_categoria_id' => '17','descripcion' => 'Multicanales para telegrafía'),
                  array('id' => '518','codigo' => '16010-0021','sub_categoria_id' => '17','descripcion' => 'Pilas húmedas o de gravedad'),
                  array('id' => '519','codigo' => '16010-0022','sub_categoria_id' => '17','descripcion' => 'Plantas eléctricas'),
                  array('id' => '520','codigo' => '16010-0023','sub_categoria_id' => '17','descripcion' => 'Probadores de tubos electrónicos'),
                  array('id' => '521','codigo' => '16010-0024','sub_categoria_id' => '17','descripcion' => 'Racks'),
                  array('id' => '522','codigo' => '16010-0025','sub_categoria_id' => '17','descripcion' => 'Radioreceptores'),
                  array('id' => '523','codigo' => '16010-0026','sub_categoria_id' => '17','descripcion' => 'Radiotransmisores'),
                  array('id' => '524','codigo' => '16010-0027','sub_categoria_id' => '17','descripcion' => 'Receptores radioeléctricos'),
                  array('id' => '525','codigo' => '16010-0028','sub_categoria_id' => '17','descripcion' => 'Rectificadores'),
                  array('id' => '526','codigo' => '16010-0029','sub_categoria_id' => '17','descripcion' => 'Teléfonos'),
                  array('id' => '527','codigo' => '16010-0030','sub_categoria_id' => '17','descripcion' => 'Teleimpresoras'),
                  array('id' => '528','codigo' => '16010-0031','sub_categoria_id' => '17','descripcion' => 'Teletipos'),
                  array('id' => '529','codigo' => '16010-0032','sub_categoria_id' => '17','descripcion' => 'Transmisores radioeléctricos'),
                  array('id' => '530','codigo' => '16010-0033','sub_categoria_id' => '17','descripcion' => 'Trazadores de señales'),
                  array('id' => '531','codigo' => '16010-0034','sub_categoria_id' => '17','descripcion' => 'Voltímetros'),


                  array('id' => '532','codigo' => '16020-0001','sub_categoria_id' => '18','descripcion' => 'Balizas'),
                  array('id' => '533','codigo' => '16020-0002','sub_categoria_id' => '18','descripcion' => 'Boyas'),
                  array('id' => '534','codigo' => '16020-0003','sub_categoria_id' => '18','descripcion' => 'Faros'),
                  array('id' => '535','codigo' => '16020-0004','sub_categoria_id' => '18','descripcion' => 'Semáforos'),


                  array('id' => '536','codigo' => '16030-0001','sub_categoria_id' => '19','descripcion' => 'Equipos de control de tráfico aéreo'),

                  array('id' => '537','codigo' => '16040-0001','sub_categoria_id' => '20','descripcion' => 'Equipos de correo'),


                  array('id' => '538','codigo' => '16990-0001','sub_categoria_id' => '21','descripcion' => 'Otros equipos de comunicaciones y señalamiento'),


                  array('id' => '539','codigo' => '17010-0001','sub_categoria_id' => '22','descripcion' => 'Agitadores de pipetas'),
                  array('id' => '540','codigo' => '17010-0002','sub_categoria_id' => '22','descripcion' => 'Agitadores serológicos'),
                  array('id' => '541','codigo' => '17010-0003','sub_categoria_id' => '22','descripcion' => 'Analizadores de cido-alcalinidad de la sangre'),
                  array('id' => '542','codigo' => '17010-0004','sub_categoria_id' => '22','descripcion' => 'Anteojos para prueba de vidrios ópticos'),
                  array('id' => '543','codigo' => '17010-0005','sub_categoria_id' => '22','descripcion' => 'Antroscopios'),
                  array('id' => '544','codigo' => '17010-0006','sub_categoria_id' => '22','descripcion' => 'Anuscopios'),
                  array('id' => '545','codigo' => '17010-0007','sub_categoria_id' => '22','descripcion' => 'Aparatos de anestesia'),
                  array('id' => '546','codigo' => '17010-0008','sub_categoria_id' => '22','descripcion' => 'Aparatos de diatermia'),
                  array('id' => '547','codigo' => '17010-0009','sub_categoria_id' => '22','descripcion' => 'Aparatos de galvanización y electroterapia'),
                  array('id' => '548','codigo' => '17010-0010','sub_categoria_id' => '22','descripcion' => 'Aparatos de hidroterapia'),
                  array('id' => '549','codigo' => '17010-0011','sub_categoria_id' => '22','descripcion' => 'Aparatos de luz ultravioleta'),
                  array('id' => '550','codigo' => '17010-0012','sub_categoria_id' => '22','descripcion' => 'Aparatos de metabolismo basal'),
                  array('id' => '551','codigo' => '17010-0013','sub_categoria_id' => '22','descripcion' => 'Aparatos de presión venosa'),
				);
        //insert manual a una base de datos con array
        \DB::table('tipos_subcat')->insert($tipo_subcat);
    }
}